trigger: none

pool:
  name: student-lab-pool

steps:
  - script: |
      /azagent/venv/bin/pip3 install pytest requests
    displayName: "Install dependencies"

variables:
  - group: LogAnalyticsSecrets

  - script: |
      export LOG_ANALYTICS_WORKSPACE_ID=$(LOG_ANALYTICS_WORKSPACE_ID)
      export LOG_ANALYTICS_SHARED_KEY=$(LOG_ANALYTICS_SHARED_KEY)
      /azagent/venv/bin/python3 -m pytest -v --tb=line  -W "ignore::DeprecationWarning" -s tests/smoke_tests_centralized.py --junitxml=smoke-results.xml


  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: 'smoke-results.xml'
      testRunTitle: 'Post-deployment Smoke Test'
      failTaskOnFailedTests: false